---
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - cd national_parks
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files: '*'
  base-directory: './national_parks/build/'

cache:
  paths:
    - '/root/.npm/**/*'
